site_name: electronick.co
site_url: https://electronick.co
theme:
  name: material
  language: en
  features:
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow    


plugins:
  - search
  - blog




# Page tree
nav:
  - Home: index.md
  - Projects: 
    - Projects/projects.md
    - Art: Projects/art.md
    - Idea bucket: Projects/ideas.md
  - Nick's Blog: 
    - blog/index.md